### ISSUE TITLE
Add color for TypeScript types

### ISSUE THREAD

**Issue by hstaudacher** [ctjdr/pure-sheet-vscode#1]
**Describe the bug**
TypeScript types use an odd color

**Expected behavior**
Probably it would be good to treat types the same as classes, see:
<img width="261" alt="Screenshot 2023-01-02 at 09 21 00" src="https://user-images.githubusercontent.com/289648/210207751-7003b2c4-270a-43e3-860e-5e0839346035.png">

**Screenshots**

<img width="285" alt="Screenshot 2023-01-02 at 09 19 42" src="https://user-images.githubusercontent.com/289648/210207641-a9531957-ed16-466a-aa9b-7b2166c5168a.png">

**Comment by hstaudacher** [comment]
When looking at the screenshot I think the token `type` can be highlighted as well the same way as `class`

**Comment by ctjdr** [comment]
You are right, all keywords (like `type`) should have the redish color. I also agree that a type name should have the same color as a class name.

**Comment by ctjdr** [comment]
Type declarations after fix:
![image](https://user-images.githubusercontent.com/14806510/210269258-498fe0cd-81fc-43b2-b6b6-55adc72bffe9.png)

**Comment by hstaudacher** [comment]
Very cool! Thank you.
