### ISSUE TITLE
TypeScript variable colors not consistent

### ISSUE THREAD

**Issue by hstaudacher** [ctjdr/pure-sheet-vscode#2]
**Describe the bug**
Variable color is not consistent

**To Reproduce**
Declare a variable or const. Use the variable

**Expected behavior**
The variable should have the same brownish color when it's declared also when it's used

**Screenshots**
<img width="186" alt="Screenshot 2023-01-05 at 10 14 11" src="https://user-images.githubusercontent.com/289648/210744287-a0ad4330-9062-4d4d-a325-5be4d5e8ffbe.png">

**Comment by ctjdr** [comment]
I can confirm that the brownish color is the intended one. Bug affects all supported languages.

**Comment by ctjdr** [comment]
Fixed variable colors.

**Comment by hstaudacher** [comment]
Verified. Looks good. Thanks for the fix!
