### ISSUE TITLE
Add color for TypeScript `instanceof`

### ISSUE THREAD

**Issue by hstaudacher** [ctjdr/pure-sheet-vscode#3]
**Describe the bug**
I have noticed that `instanceof` is not colored in typescript.

**To Reproduce**
```ts
if( x instanceof Y ) 
```

**Screenshots**
<img width="363" alt="Screenshot 2023-06-14 at 16 13 36" src="https://github.com/ctjdr/pure-sheet-vscode/assets/289648/6f252a5f-1b76-44c9-8a72-596d850c6d23">

**Comment by ctjdr** [comment]
Fixed with v0.0.10. Thanks for reporting!
